name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    
    - name: Run basic syntax check
      run: |
        python -m py_compile src/updater.py
        echo "✅ Syntax check passed"
    
    - name: Test cross-platform imports
      run: |
        python -c "
        import subprocess
        import datetime
        import platform
        import os
        import sys
        from pathlib import Path
        print('✅ All imports successful')
        "

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
    
    - name: Lint with flake8
      run: |
        flake8 src/ --count --show-source --statistics --max-line-length=127
    
    - name: Lint with pylint
      run: |
        pylint src/ --exit-zero
