name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Create release archive
      run: |
        mkdir release
        cp -r src/ release/
        cp README.md release/
        cp requirements.txt release/
        cp LICENSE release/
        zip -r system-updater-${{ github.ref_name }}.zip release/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: system-updater-${{ github.ref_name }}.zip
        generate_release_notes: true
